config/routes.rb
Rails.application.routes.draw do
  get 'reactions/create'
  get 'reactions/destroy'
  devise_for :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
  resources :users, only: [:show] do
    member do
      get :followings, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

  resources :tweets do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
    resources :reactions, only: [:create, :destroy]
  end

  resources :players, only: [:index, :show] do
    post 'coorde', on: :collection
  end
end
  
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :content, presence: true
end

app/models/coordinate.rb
class Coordinate < ApplicationRecord
    has_many :player_coordinates
    has_many :players, through: :player_coordinates
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :player_coordinates
    has_many :coordinates, through: :player_coordinates
  
    def total_stats
      base_stats = {
        attack: self.attack,
        defense: self.defense,
      }
  
      coordinates.each do |coordinate|
        base_stats[:attack] += coordinate.attack
        base_stats[:defense] += coordinate.defense
      end
  
      base_stats
    end
end

app/models/player_coordinate.rb
class PlayerCoordinate < ApplicationRecord
    belongs_to :player
    belongs_to :coordinate
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  validates_length_of :emoji, maximum: 1
  validate :emoji_only

  private
  def emoji_only
    unless emoji.match?(/[\p{Emoji}]/)
      errors.add(:emoji, "must contain only emojis")
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user 

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy

  mount_uploader :image, ImageUploader
  mount_uploader :audio, AudioUploader
  mount_uploader :video, VideoUploader

  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
  has_many :comments, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :reactions, dependent: :destroy

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
before_action :authenticate_user!

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)

    tweet.user_id = current_user.id

    if tweet.save
      flash[:notice] = '投稿どね'
      redirect_to :action => "index"     
    else
      flash[:notice] = '投稿できないよ。どんまい'
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])

    @comments = @tweet.comments
    @comment = Comment.new
    @reactions = @tweet.reactions
    @reaction = Reaction.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      flash[:notice] = '編集どね'
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    flash[:notice] = '削除どね'
    redirect_to action: :index
  end
  
  private
  def tweet_params
    params.require(:tweet).permit(:body, :image, :audio, :video, :level)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/emoji_helper.rb
module EmojiHelper
    def emojify(content)
      h(content).to_str.gsub(/:([\w+-]+):/) do |match|
        if emoji = Emoji.find_by_alias($1)
          path = "/images/emoji/#{emoji.image_filename}"
          %(<img alt="#$1" src="#{path}" style="vertical-align:middle" width="20" height="20" />)
        else
          match
        end
      end.html_safe if content.present?
    end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集どね" %>
  <% end %>

app/views/tweets/index.html.erb
<%= t(".hello_html")%>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>


<div class="tweets-container">
  <% @tweets.each do |t| %>
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
    <%= audio_tag t.audio_url, :controls => true if t.audio? %>

    <%= link_to t.user.name, user_path(t.user.id) %>


    <%= link_to (tweet_path(t.id)) do %>
      <div class="tweet">
        <%= t.body %>
        <%= t.created_at %>

          <% if current_user.already_liked?(t) %>
              <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
            <% else %>
              <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
        
        <i class="far fa-heart"></i><%= t.likes.count %>
      </div> 
    <% end %>

    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "削除する", tweet_path(t.id), method: :delete %>
    <% end %> 
  <% end %>
</div>




<%= link_to "新規投稿ページへ", new_tweet_path %>
<%= link_to "選手攻略サイトへ", players_path %>

app/views/tweets/new.html.erb
<%= t(".neww_html")%>
<%= flash[:notice] %>

<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, title: t('helpers.choose_file')  %>
  </div>

  <div class="field">
    <%= f.label :video %>
    <%= f.file_field :video, title:  t('helpers.choose_file'), :accept => 'video/*' %>
  </div>

  <div class="field">
    <%= f.label :audio %>
    <%= f.file_field :audio, title:  t('helpers.choose_file') %>
  </div>

  <h5>授業レベル</h5>
  <div class="post_form">
    <%= f.radio_button :level,  5 ,id: 'star6'%>
    <label for="star6"><span class="text">難しい</span>★</label>

    <%= f.radio_button :level,  4 ,id: 'star7'%>
    <label for="star7"><span class="text">やや難しい</span>★</label>

    <%= f.radio_button :level, 3 ,id: 'star8'%>
    <label for="star8"><span class="text">普通</span>★</label>

    <%= f.radio_button :level , 2 ,id: 'star9'%>
    <label for="star9"><span class="text">やや簡単</span>★</label>

    <%= f.radio_button :level , 1 ,id: 'star10'%>
    <label for="star10"><span class="text">簡単</span>★</label>
  </div>

  <%= f.submit %>
<% end %>

<%= link_to t('links.index'), tweets_path %>

app/views/tweets/show.html.erb
<h3>Tweet詳細</h3>
<%= flash[:notice] %>

<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
  <p>
    <%= link_to @tweet.video_url.to_s do %>
      <%= video_tag(@tweet.video.to_s) %>
    <% end %>
  </p>


  <% if current_user.already_liked?(@tweet) %>
      <%= link_to tweet_like_path(@tweet), method: :delete do %>
        <i class="fas fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
    <% else %>
      <%= link_to tweet_likes_path(@tweet), method: :post do %>
        <i class="fas fa-heart"></i><%= @tweet.likes.count %>
      <% end %>
  <% end %>

  <i class="fas fa-heart"></i><%= @tweet.likes.count %>

  <%= image_tag @tweet.image_url, size: "250x200" if @tweet.image? %>

  <% if user_signed_in? && current_user.id == @tweet.user_id %>
    <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
    <%= link_to "削除する", tweet_path(@tweet.id), method: :delete %>
  <% end %>
</div>

<div class="reaction-wrapper">
  <p>リアクション一覧</p>
  <% @reactions.each do |c| %>
    <details>
      <%= c.user.email if c.user %>
      <summary>
        <%= emojify(c.emoji) %>
      </summary>
    </details>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @reaction], local: true) do |f| %>
      <%= f.text_field :emoji, id: "emoji_field" %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i>リアクションする
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>

<script>
document.addEventListener("DOMContentLoaded", function() {
  var emojiField = document.getElementById("emoji_field");
  emojiField.addEventListener("input", function() {
    var emojiRegex = /[\p{Emoji}]/u; // 絵文字の正規表現
    if (!emojiRegex.test(this.value)) {
      this.value = ''; // 絵文字以外の入力をクリア
      alert('Please enter only emojis.');
    }
  });
});
</script>